apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: testdeploy1
  name: testdeploy1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testdeploy1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: testdeploy1
    spec:
      containers:
      - image: springio/gs-spring-boot-docker
        name: gs-spring-boot-docker
        resources: {}
status: {}
